# Generated by Django 5.0.7 on 2024-11-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_comentario_vehiculo_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenauto',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cantidad_puertas',
            field=models.IntegerField(verbose_name='Cantidad de Puertas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.FloatField(default=0, verbose_name='Cilindrada'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fabricado_el',
            field=models.IntegerField(default=2024, verbose_name='Año de Fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='vehiculos.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pais_fabricacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.pais_fabricacion', verbose_name='País de Fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio_dolares',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio en USD'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.tipo_combustible', verbose_name='Tipo de Combustible'),
        ),
    ]
