# Generated by Django 5.0.7 on 2024-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_alter_imagenauto_vehiculo_alter_vehiculo_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Color'),
        ),
    ]
