# Generated by Django 5.0.7 on 2024-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_alter_color_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
